### PR TITLE
Fix mobile navigation layout with hamburger menu

### LINKED ISSUE #164: Update mobile navigation to a hamburger menu and update link hierarchy
At events when we direct people to go to Toronto JS website, they usually are looking for links to join slack and how to volunteer.

The issue is that on mobile the links show only as icons and it is not very intuitive for users what icon does what, so we could benefit for another type of navigation, like a hamburger menu that shows text alongside with the icons.

Also, to make it easier to users to navigate, we should reorganize the links so the most used ones are first on the menu.

### PR DESCRIPTION
**Pull request by Gursimran07316**
This PR improves the mobile layout for the navigation menu.
Adjustments include adding a hamburger menu with both icons and text for better clarity and navigation.
Fixes #164 
Before
Screenshot 2025-02-23 at 12 53 13 PM
After 
Screenshot 2025-02-23 at 1 00 37 PM
Screenshot 2025-02-23 at 1 00 09 PM

### CODE REVIEW

**Review by kieran — COMMENTED** [review]
love this so far!

File: components/navbar/index.coffee [hunk 1]
```diff
@@ -1,74 +1,62 @@
...
+  FaBars,
+  FaTimes
 } from 'react-icons/fa'
 
 import GuildLogo from './guild_logo.png'
-
 import './styles.sass'
 
-export default Navbar = ({ afterDark = false }) ->
+Navbar = ({ afterDark = false }) ->
```
Comment (kieran) [inline components/navbar/index.coffee:18]: it totally valid to do the export here in coffee, ok to put it back?

File: components/navbar/styles.sass [hunk 2]
```diff
@@ -28,13 +32,48 @@ nav.Navbar
...
+      padding: 1em
+      display: flex
+      justify-content: flex-start
+      line-height: 0
 
-    +tablet
-      span.label
-        display: none
+    .nav-links.open
+      display: flex
```
Comment (kieran) [inline components/navbar/styles.sass:79]: # suggestion:

```sass
    background: #0a0a1e // or var(--color-red) for light mode
    align-items: flex-start
```

## before
image
image


## after

image
image

Comment (kieran) [reply components/navbar/styles.sass:79]: lmk if you need help with the light/dark rules

File: components/navbar/index.coffee (hunk 1 above)
Comment (Gursimran07316) [reply components/navbar/index.coffee]: Done!!

File: components/navbar/styles.sass (hunk 2 above)
Comment (Gursimran07316) [reply components/navbar/styles.sass:81]: I've implemented all the suggested changes. I really enjoyed working on this! Let me know if any further improvements are needed—always happy to refine things!

**Review by kieran — APPROVED** [review]
Beautiful work, Gursimrandeep.

Thanks!
